<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class CoaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = DB::table('category_coas')->pluck('id', 'category_name');

        $accounts = [

            // START DATA VERSI INDO

            // KATEGORI ASET LANCAR
            ['name' => 'Kas', 'coa_no' => '100.000',  'coa_category_id' => 'ASET LANCAR', 'amount' => 0, 'description' => 'ASET LANCAR', 'type' => 'Debit'],
            ['name' => 'Kas Kecil', 'coa_no' => '100.001',  'coa_category_id' => 'ASET LANCAR', 'amount' => 0, 'description' => 'ASET LANCAR', 'type' => 'Debit'],
            ['name' => 'Kas Kecil 2', 'coa_no' => '100.002',  'coa_category_id' => 'ASET LANCAR', 'amount' => 0, 'description' => 'ASET LANCAR', 'type' => 'Debit'],
            ['name' => 'Bank', 'coa_no' => '101.000',  'coa_category_id' => 'ASET LANCAR', 'amount' => 0, 'description' => 'ASET LANCAR', 'type' => 'Debit'],
            ['name' => 'BCA 519.087.8998', 'coa_no' => '101.001',  'coa_category_id' => 'ASET LANCAR', 'amount' => 0, 'description' => 'ASET LANCAR', 'type' => 'Debit'],
            ['name' => 'BTN 00062.01.30.000910.4', 'coa_no' => '101.002',  'coa_category_id' => 'ASET LANCAR', 'amount' => 0, 'description' => 'ASET LANCAR', 'type' => 'Debit'],
            ['name' => 'BNI 6777116688', 'coa_no' => '101.003',  'coa_category_id' => 'ASET LANCAR', 'amount' => 0, 'description' => 'ASET LANCAR', 'type' => 'Debit'],
            ['name' => 'BANK UOB 372-302-305-8', 'coa_no' => '101.004',  'coa_category_id' => 'ASET LANCAR', 'amount' => 0, 'description' => 'ASET LANCAR', 'type' => 'Debit'],
            ['name' => 'KAS & SETARA KAS LAINNYA', 'coa_no' => '102.000',  'coa_category_id' => 'ASET LANCAR', 'amount' => 0, 'description' => 'ASET LANCAR', 'type' => 'Debit'],
            ['name' => 'Deposito', 'coa_no' => '102.001',  'coa_category_id' => 'ASET LANCAR', 'amount' => 0, 'description' => 'ASET LANCAR', 'type' => 'Debit'],
            ['name' => 'Voucher', 'coa_no' => '102.002',  'coa_category_id' => 'ASET LANCAR', 'amount' => 0, 'description' => 'ASET LANCAR', 'type' => 'Debit'],
            ['name' => 'Kas Penampung / ayat silang', 'coa_no' => '102.999',  'coa_category_id' => 'ASET LANCAR', 'amount' => 0, 'description' => 'ASET LANCAR', 'type' => 'Debit'],
            ['name' => 'PIUTANG USAHA', 'coa_no' => '110.000',  'coa_category_id' => 'ASET LANCAR', 'amount' => 0, 'description' => 'ASET LANCAR', 'type' => 'Debit'],
            ['name' => 'Piutang Jasa', 'coa_no' => '110.001',  'coa_category_id' => 'ASET LANCAR', 'amount' => 0, 'description' => 'ASET LANCAR', 'type' => 'Debit'],
            ['name' => 'PIUTANG LAIN-LAIN', 'coa_no' => '120.000',  'coa_category_id' => 'ASET LANCAR', 'amount' => 0, 'description' => 'ASET LANCAR', 'type' => 'Debit'],
            ['name' => 'Piutang Karyawan', 'coa_no' => '120.001',  'coa_category_id' => 'ASET LANCAR', 'amount' => 0, 'description' => 'ASET LANCAR', 'type' => 'Debit'],
            ['name' => 'Piutang Direksi', 'coa_no' => '120.002',  'coa_category_id' => 'ASET LANCAR', 'amount' => 0, 'description' => 'ASET LANCAR', 'type' => 'Debit'],
            ['name' => 'Piutang Yayasan', 'coa_no' => '120.003',  'coa_category_id' => 'ASET LANCAR', 'amount' => 0, 'description' => 'ASET LANCAR', 'type' => 'Debit'],
            ['name' => 'Piutang Afiliasi (Yes Learning)', 'coa_no' => '120.004',  'coa_category_id' => 'ASET LANCAR', 'amount' => 0, 'description' => 'ASET LANCAR', 'type' => 'Debit'],
            ['name' => 'Piutang Capital Fee', 'coa_no' => '120.005',  'coa_category_id' => 'ASET LANCAR', 'amount' => 0, 'description' => 'ASET LANCAR', 'type' => 'Debit'],
            ['name' => 'Piutang Material Fee', 'coa_no' => '120.006',  'coa_category_id' => 'ASET LANCAR', 'amount' => 0, 'description' => 'ASET LANCAR', 'type' => 'Debit'],
            ['name' => 'Piutang Monthly Fee', 'coa_no' => '120.007',  'coa_category_id' => 'ASET LANCAR', 'amount' => 0, 'description' => 'ASET LANCAR', 'type' => 'Debit'],
            ['name' => 'Piutang lain nya (edu save)', 'coa_no' => '120.008',  'coa_category_id' => 'ASET LANCAR', 'amount' => 0, 'description' => 'ASET LANCAR', 'type' => 'Debit'],
            ['name' => 'Piutang lain nya (Graduation)', 'coa_no' => '120.009',  'coa_category_id' => 'ASET LANCAR', 'amount' => 0, 'description' => 'ASET LANCAR', 'type' => 'Debit'],
            ['name' => 'Piutang lain nya (Robotic)', 'coa_no' => '120.010',  'coa_category_id' => 'ASET LANCAR', 'amount' => 0, 'description' => 'ASET LANCAR', 'type' => 'Debit'],
            ['name' => 'Piutang lainnya (Cambridge)', 'coa_no' => '120.011',  'coa_category_id' => 'ASET LANCAR', 'amount' => 0, 'description' => 'ASET LANCAR', 'type' => 'Debit'],
            ['name' => 'Piutang lainnya (Event)', 'coa_no' => '120.012',  'coa_category_id' => 'ASET LANCAR', 'amount' => 0, 'description' => 'ASET LANCAR', 'type' => 'Debit'],
            ['name' => 'Piutang Registration fee', 'coa_no' => '120.013',  'coa_category_id' => 'ASET LANCAR', 'amount' => 0, 'description' => 'ASET LANCAR', 'type' => 'Debit'],
            ['name' => 'Piutang Pihak Ketiga', 'coa_no' => '120.014',  'coa_category_id' => 'ASET LANCAR', 'amount' => 0, 'description' => 'ASET LANCAR', 'type' => 'Debit'],
            // ['name' => 'Piutang Lain-lain', 'coa_no' => '120.999',  'coa_category_id' => 'ASET LANCAR', 'amount' => 0, 'description' => 'ASET LANCAR'],

            // KATEGORI PAJAK DIBAYAR DIMUKA
            ['name' => 'PPh Pasal 21', 'coa_no' => '130.001',  'coa_category_id' => 'PAJAK DIBAYAR DIMUKA', 'amount' => 0, 'description' => 'PAJAK DIBAYAR DIMUKA', 'type' => 'Debit'],
            ['name' => 'PPh Pasal 22', 'coa_no' => '130.002',  'coa_category_id' => 'PAJAK DIBAYAR DIMUKA', 'amount' => 0, 'description' => 'PAJAK DIBAYAR DIMUKA', 'type' => 'Debit'],
            ['name' => 'PPh Pasal 23', 'coa_no' => '130.003',  'coa_category_id' => 'PAJAK DIBAYAR DIMUKA', 'amount' => 0, 'description' => 'PAJAK DIBAYAR DIMUKA', 'type' => 'Debit'],
            ['name' => 'PPh Pasal 24', 'coa_no' => '130.004',  'coa_category_id' => 'PAJAK DIBAYAR DIMUKA', 'amount' => 0, 'description' => 'PAJAK DIBAYAR DIMUKA', 'type' => 'Debit'],
            ['name' => 'PPh Pasal 25', 'coa_no' => '130.005',  'coa_category_id' => 'PAJAK DIBAYAR DIMUKA', 'amount' => 0, 'description' => 'PAJAK DIBAYAR DIMUKA', 'type' => 'Debit'],
            ['name' => 'PPh Pasal 26', 'coa_no' => '130.006',  'coa_category_id' => 'PAJAK DIBAYAR DIMUKA', 'amount' => 0, 'description' => 'PAJAK DIBAYAR DIMUKA', 'type' => 'Debit'],
            ['name' => 'PPN Masukan', 'coa_no' => '130.007',  'coa_category_id' => 'PAJAK DIBAYAR DIMUKA', 'amount' => 0, 'description' => 'PAJAK DIBAYAR DIMUKA', 'type' => 'Debit'],
            ['name' => 'PPh Pasal 29', 'coa_no' => '130.009',  'coa_category_id' => 'PAJAK DIBAYAR DIMUKA', 'amount' => 0, 'description' => 'PAJAK DIBAYAR DIMUKA', 'type' => 'Debit'],

            // KATEGORI PERSEDIAAN
            ['name' => 'PERSEDIAAN', 'coa_no' => '140.000',  'coa_category_id' => 'PERSEDIAAN', 'amount' => 0, 'description' => 'PERSEDIAAN', 'type' => 'Debit'],
            ['name' => 'UANG MUKA PEMBELIAN', 'coa_no' => '150.000',  'coa_category_id' => 'PERSEDIAAN', 'amount' => 0, 'description' => 'PERSEDIAAN', 'type' => 'Debit'],
            ['name' => 'UM Pembelian', 'coa_no' => '150.001',  'coa_category_id' => 'PERSEDIAAN', 'amount' => 0, 'description' => 'PERSEDIAAN', 'type' => 'Debit'],
            ['name' => 'UM Pembelian Lain-lain', 'coa_no' => '150.002',  'coa_category_id' => 'PERSEDIAAN', 'amount' => 0, 'description' => 'PERSEDIAAN', 'type' => 'Debit'],
            ['name' => 'BIAYA DIBAYAR DIMUKA', 'coa_no' => '160.000',  'coa_category_id' => 'PERSEDIAAN', 'amount' => 0, 'description' => 'PERSEDIAAN', 'type' => 'Debit'],
            ['name' => 'Asuransi Dibayar Dimuka', 'coa_no' => '160.001',  'coa_category_id' => 'PERSEDIAAN', 'amount' => 0, 'description' => 'PERSEDIAAN', 'type' => 'Debit'],
            ['name' => 'Sewa Dibayar Dimuka', 'coa_no' => '160.002',  'coa_category_id' => 'PERSEDIAAN', 'amount' => 0, 'description' => 'PERSEDIAAN', 'type' => 'Debit'],
            ['name' => 'Biaya Dibayar Dimuka Lain-lain', 'coa_no' => '160.999',  'coa_category_id' => 'PERSEDIAAN', 'amount' => 0, 'description' => 'PERSEDIAAN', 'type' => 'Debit'],

            // KATEGORI ASET TIDAK LANCAR
            ['name' => 'ASET TETAP', 'coa_no' => '170.000',  'coa_category_id' => 'ASET TIDAK LANCAR', 'amount' => 0, 'description' => 'ASET TIDAK LANCAR', 'type' => 'Debit'],
            ['name' => 'Tanah', 'coa_no' => '170.001',  'coa_category_id' => 'ASET TIDAK LANCAR', 'amount' => 0, 'description' => 'ASET TIDAK LANCAR', 'type' => 'Debit'],
            ['name' => 'Bangunan', 'coa_no' => '170.002',  'coa_category_id' => 'ASET TIDAK LANCAR', 'amount' => 0, 'description' => 'ASET TIDAK LANCAR', 'type' => 'Debit'],
            ['name' => 'Kendaraan', 'coa_no' => '170.003',  'coa_category_id' => 'ASET TIDAK LANCAR', 'amount' => 0, 'description' => 'ASET TIDAK LANCAR', 'type' => 'Debit'],
            ['name' => 'Inventaris Sekolah', 'coa_no' => '170.004',  'coa_category_id' => 'ASET TIDAK LANCAR', 'amount' => 0, 'description' => 'ASET TIDAK LANCAR', 'type' => 'Debit'],
            ['name' => 'Sarana & Instalasi', 'coa_no' => '170.005',  'coa_category_id' => 'ASET TIDAK LANCAR', 'amount' => 0, 'description' => 'ASET TIDAK LANCAR', 'type' => 'Debit'],
            ['name' => 'Akumulasi Penyusutan Bangunan', 'coa_no' => '171.002',  'coa_category_id' => 'ASET TIDAK LANCAR', 'amount' => 0, 'description' => 'ASET TIDAK LANCAR', 'type' => 'Kredit'],
            ['name' => 'Akumulasi Penyusutan Kendaraan', 'coa_no' => '171.003',  'coa_category_id' => 'ASET TIDAK LANCAR', 'amount' => 0, 'description' => 'ASET TIDAK LANCAR', 'type' => 'Kredit'],
            ['name' => 'Akumulasi Penyusutan Inventaris Sekolah', 'coa_no' => '171.004',  'coa_category_id' => 'ASET TIDAK LANCAR', 'amount' => 0, 'description' => 'ASET TIDAK LANCAR', 'type' => 'Kredit'],
            ['name' => 'Akumulasi Penyusutan Sarana & Instalasi', 'coa_no' => '171.005',  'coa_category_id' => 'ASET TIDAK LANCAR', 'amount' => 0, 'description' => 'ASET TIDAK LANCAR', 'type' => 'Kredit'],
            ['name' => 'Akumulasi Penyusutan Mesin', 'coa_no' => '171.006',  'coa_category_id' => 'ASET TIDAK LANCAR', 'amount' => 0, 'description' => 'ASET TIDAK LANCAR', 'type' => 'Kredit'],
            ['name' => 'ASET TAK BERWUJUD', 'coa_no' => '180.000',  'coa_category_id' => 'ASET TIDAK LANCAR', 'amount' => 0, 'description' => 'ASET TIDAK LANCAR', 'type' => 'Debit'],
            ['name' => 'Harta Tidak Berwujud', 'coa_no' => '180.001',  'coa_category_id' => 'ASET TIDAK LANCAR', 'amount' => 0, 'description' => 'ASET TIDAK LANCAR', 'type' => 'Debit'],
            ['name' => 'AMORTISASI', 'coa_no' => '180.002',  'coa_category_id' => 'ASET TIDAK LANCAR', 'amount' => 0, 'description' => 'ASET TIDAK LANCAR', 'type' => 'Debit'],
            ['name' => 'Amortisasi Harta Tidak Berwujud', 'coa_no' => '180.003',  'coa_category_id' => 'ASET TIDAK LANCAR', 'amount' => 0, 'description' => 'ASET TIDAK LANCAR', 'type' => 'Debit'],
            ['name' => 'ASET LAIN - LAIN', 'coa_no' => '190.000',  'coa_category_id' => 'ASET TIDAK LANCAR', 'amount' => 0, 'description' => 'ASET TIDAK LANCAR', 'type' => 'Debit'],
            ['name' => 'Jaminan', 'coa_no' => '190.001',  'coa_category_id' => 'ASET TIDAK LANCAR', 'amount' => 0, 'description' => 'ASET TIDAK LANCAR', 'type' => 'Debit'],
            ['name' => 'Aset dalam Penyelesaian', 'coa_no' => '190.002',  'coa_category_id' => 'ASET TIDAK LANCAR', 'amount' => 0, 'description' => 'ASET TIDAK LANCAR', 'type' => 'Debit'],

            // KATEGORI KEWAJIBAN LANCAR
            ['name' => 'HUTANG BANK', 'coa_no' => '200.000',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'HUTANG DAGANG', 'coa_no' => '210.000',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Debit'],
            ['name' => 'Hutang Jasa', 'coa_no' => '210.001',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'HUTANG LAIN-LAIN', 'coa_no' => '220.000',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'Hutang Karyawan', 'coa_no' => '220.001',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'Hutang Direksi', 'coa_no' => '220.002',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'Hutang Yayasan', 'coa_no' => '220.003',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'Hutang Pihak Ketiga', 'coa_no' => '220.004',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'BIAYA YANG MASIH HARUS DIBAYAR', 'coa_no' => '230.000',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'Hutang Gaji', 'coa_no' => '230.001',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'Hutang Usaha', 'coa_no' => '230.002',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'Hutang Kendaraan', 'coa_no' => '230.003',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'Titipan material fee', 'coa_no' => '230.004',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'BYMHD Lain-lain', 'coa_no' => '230.999',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'HUTANG PAJAK', 'coa_no' => '240.000',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'Hutang PPh Pasal 21', 'coa_no' => '240.001',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'Hutang PPh Pasal 22', 'coa_no' => '240.002',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'Hutang PPh Pasal 23', 'coa_no' => '240.003',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'Hutang PPh Pasal 24', 'coa_no' => '240.004',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'Hutang PPh Pasal 25', 'coa_no' => '240.005',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'Hutang PPh Pasal 26', 'coa_no' => '240.006',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'Hutang PPN', 'coa_no' => '240.007',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'Hutang PPh Final Pasal 4 Ayat (2)', 'coa_no' => '240.008',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'Hutang PPh Pasal 29', 'coa_no' => '240.009',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'Hutang PP 23 tahun 2018', 'coa_no' => '240.010',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'PENDAPATAN DITERIMA DIMUKA', 'coa_no' => '250.000',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'Monthly Fee Diterima Dimuka', 'coa_no' => '250.001',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'Capital Fee Diterima Dimuka', 'coa_no' => '250.002',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'Material Fee Diterima Dimuka', 'coa_no' => '250.003',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'Simpanan Edusave Diterima Dimuka', 'coa_no' => '250.004',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'Registrasi Fee Diterima Dimuka', 'coa_no' => '250.005',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'Fieldtrip Diterima Dimuka', 'coa_no' => '250.006',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'ILP Diterima Dimuka', 'coa_no' => '250.007',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'Robotik Diterima Dimuka', 'coa_no' => '250.008',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'Shadow Teacher Diterima Dimuka', 'coa_no' => '250.009',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'Kyukusinkai Diterima Dimuka', 'coa_no' => '250.010',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'Cooking Class Diterima Dimuka', 'coa_no' => '250.011',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'Antar Jemput Diterima Dimuka', 'coa_no' => '250.012',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'Jurnal Book & Buku Tulis Diterima Dimuka', 'coa_no' => '250.013',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],
            ['name' => 'Cambridge Check Point & Graduation Diterima Dimuka', 'coa_no' => '250.014',  'coa_category_id' => 'KEWAJIBAN LANCAR', 'amount' => 0, 'description' => 'KEWAJIBAN LANCAR', 'type' => 'Kredit'],

            // KATEGORI KEWAJIBAN JANGKA PANJANG
            ['name' => 'HUTANG JANGKA PANJANG', 'coa_no' => '260.000',  'coa_category_id' => 'KEWAJIBAN JANGKA PANJANG', 'amount' => 0, 'description' => 'KEWAJIBAN JANGKA PANJANG', 'type' => 'Kredit'],

            // KATEGORI EKUITAS
            ['name' => 'MODAL', 'coa_no' => '300.000',  'coa_category_id' => 'EKUITAS', 'amount' => 0, 'description' => 'EKUITAS', 'type' => 'Kredit'],
            ['name' => 'SELISIH LEBIH (KURANG)', 'coa_no' => '310.000',  'coa_category_id' => 'EKUITAS', 'amount' => 0, 'description' => 'EKUITAS', 'type' => 'Kredit'],
            ['name' => 'Selisih Lebih (Kurang) Ditahan', 'coa_no' => '310.001',  'coa_category_id' => 'EKUITAS', 'amount' => 0, 'description' => 'EKUITAS', 'type' => 'Kredit'],
            ['name' => 'Selisih Lebih (Kurang) Berjalan', 'coa_no' => '310.002',  'coa_category_id' => 'EKUITAS', 'amount' => 0, 'description' => 'EKUITAS', 'type' => 'Kredit'],

            // KATEGORI PENDAPATAN
            ['name' => 'Pendapatan', 'coa_no' => '400.000', 'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Kredit'],
            ['name' => 'Monthly Fee', 'coa_no' => '400.001', 'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Kredit'],
            ['name' => 'Capital Fee', 'coa_no' => '400.002', 'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Kredit'],
            ['name' => 'Material Fee', 'coa_no' => '400.003', 'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Kredit'],
            ['name' => 'Edusave', 'coa_no' => '400.004', 'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Kredit'],
            ['name' => 'Registrasi Fee', 'coa_no' => '400.005', 'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Kredit'],
            ['name' => 'Fieldtrip', 'coa_no' => '400.006', 'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Kredit'],
            ['name' => 'ILP', 'coa_no' => '400.007', 'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Kredit'],
            ['name' => 'Robotik', 'coa_no' => '400.008', 'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Kredit'],
            ['name' => 'Penjualan Jas Lab', 'coa_no' => '400.009', 'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Kredit'],
            ['name' => 'Penjualan Kain Seragam', 'coa_no' => '400.010', 'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Kredit'],
            ['name' => 'Pendapatan Kantin Sekolah', 'coa_no' => '400.011', 'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Kredit'],
            ['name' => 'Penerimaan Koperasi', 'coa_no' => '400.012', 'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Kredit'],
            ['name' => 'Pendapatan Event', 'coa_no' => '400.013', 'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Kredit'],
            ['name' => 'Penjualan Seragam PE', 'coa_no' => '400.014', 'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Kredit'],
            ['name' => 'Penjualan Swimsuit', 'coa_no' => '400.015', 'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Kredit'],
            ['name' => 'Penjualan Jurnal Book & Buku Tulis', 'coa_no' => '400.016', 'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Kredit'],
            ['name' => 'Shadow Teacher', 'coa_no' => '400.017',  'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Kredit'],
            ['name' => 'Kyukusinkai', 'coa_no' => '400.018',  'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Kredit'],
            ['name' => 'Cooking Class', 'coa_no' => '400.019',  'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Kredit'],
            ['name' => 'Pendapatan Antar Jemput', 'coa_no' => '400.020',  'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Kredit'],
            ['name' => 'Pendapatan Charge Kartu Kredit & Late Charge', 'coa_no' => '400.021',  'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Kredit'],
            ['name' => 'Health Meal', 'coa_no' => '400.022',  'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Kredit'],
            ['name' => 'Cambridge Check Point & Graduation', 'coa_no' => '400.023',  'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Kredit'],
            ['name' => 'Ujian Cambridge Igcse & As/A Level', 'coa_no' => '400.024',  'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Kredit'],
            ['name' => 'Pendapatan Sponsorship', 'coa_no' => '400.025',  'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Kredit'],
            ['name' => 'Pendapatan Afiliasi', 'coa_no' => '400.026',  'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Kredit'],
            ['name' => 'Penjualan Buku Paket Siswa', 'coa_no' => '400.027',  'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Kredit'],
            ['name' => 'Pendapatan Placement Test', 'coa_no' => '400.028',  'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Kredit'],
            ['name' => 'Pendapatan IGCSE Course', 'coa_no' => '400.029',  'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Kredit'],
            ['name' => 'Pendapatan Ujian Paket C', 'coa_no' => '400.030',  'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Kredit'],
            ['name' => 'RETUR PENDAPATAN', 'coa_no' => '410.000',  'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Debit'],
            ['name' => 'POTONGAN PENDAPATAN', 'coa_no' => '420.000',  'coa_category_id' => 'PENDAPATAN', 'amount' => 0, 'description' => 'PENDAPATAN', 'type' => 'Debit'],

            // KATEGORI BEBAN POKOK
            ['name' => 'BEBAN SARANA DAN PRASARANA', 'coa_no' => '500.000',  'coa_category_id' => 'BEBAN POKOK', 'amount' => 0, 'description' => 'BEBAN POKOK', 'type' => 'Debit'],
            ['name' => 'Pemeliharaan Fasilitas Sekolah', 'coa_no' => '500.001',  'coa_category_id' => 'BEBAN POKOK', 'amount' => 0, 'description' => 'BEBAN POKOK', 'type' => 'Debit'],
            ['name' => 'Biaya - Praktikum Sekolah', 'coa_no' => '500.002',  'coa_category_id' => 'BEBAN POKOK', 'amount' => 0, 'description' => 'BEBAN POKOK', 'type' => 'Debit'],
            ['name' => 'B. Kemitraan & Intrakurikuler', 'coa_no' => '500.003',  'coa_category_id' => 'BEBAN POKOK', 'amount' => 0, 'description' => 'BEBAN POKOK', 'type' => 'Debit'],
            ['name' => 'Biaya Material Fee', 'coa_no' => '500.004',  'coa_category_id' => 'BEBAN POKOK', 'amount' => 0, 'description' => 'BEBAN POKOK', 'type' => 'Debit'],
            ['name' => 'Biaya Graduation', 'coa_no' => '500.005',  'coa_category_id' => 'BEBAN POKOK', 'amount' => 0, 'description' => 'BEBAN POKOK', 'type' => 'Debit'],
            ['name' => 'Biaya Yes Learning', 'coa_no' => '500.006',  'coa_category_id' => 'BEBAN POKOK', 'amount' => 0, 'description' => 'BEBAN POKOK', 'type' => 'Debit'],
            ['name' => 'Biaya Gaji', 'coa_no' => '500.007',  'coa_category_id' => 'BEBAN POKOK', 'amount' => 0, 'description' => 'BEBAN POKOK', 'type' => 'Debit'],
            ['name' => 'Biaya Fieldtrip', 'coa_no' => '500.008',  'coa_category_id' => 'BEBAN POKOK', 'amount' => 0, 'description' => 'BEBAN POKOK', 'type' => 'Debit'],
            ['name' => 'BEBAN OVERHEAD', 'coa_no' => '510.000',  'coa_category_id' => 'BEBAN POKOK', 'amount' => 0, 'description' => 'BEBAN POKOK', 'type' => 'Debit'],
            ['name' => 'Listrik & PAM Sekolah', 'coa_no' => '510.001',  'coa_category_id' => 'BEBAN POKOK', 'amount' => 0, 'description' => 'BEBAN POKOK', 'type' => 'Debit'],
            ['name' => 'BEBAN PENGADAAN', 'coa_no' => '520.000',  'coa_category_id' => 'BEBAN POKOK', 'amount' => 0, 'description' => 'BEBAN POKOK', 'type' => 'Debit'],
            ['name' => 'Pengadaan Buku', 'coa_no' => '520.001',  'coa_category_id' => 'BEBAN POKOK', 'amount' => 0, 'description' => 'BEBAN POKOK', 'type' => 'Debit'],
            ['name' => 'Pengadaan Seragam', 'coa_no' => '520.002',  'coa_category_id' => 'BEBAN POKOK', 'amount' => 0, 'description' => 'BEBAN POKOK', 'type' => 'Debit'],
            ['name' => 'Pendapatan Legalisir', 'coa_no' => '520.003',  'coa_category_id' => 'BEBAN POKOK', 'amount' => 0, 'description' => 'BEBAN POKOK', 'type' => 'Debit'],

            // KATEGORI BEBAN PENJUALAN
            ['name' => 'BEBAN IKLAN DAN PROMOSI', 'coa_no' => '600.000',  'coa_category_id' => 'BEBAN PENJUALAN', 'amount' => 0, 'description' => 'BEBAN PENJUALAN', 'type' => 'Debit'],
            ['name' => 'Promosi Sekolah', 'coa_no' => '600.001',  'coa_category_id' => 'BEBAN PENJUALAN', 'amount' => 0, 'description' => 'BEBAN PENJUALAN', 'type' => 'Debit'],
            ['name' => 'Iklan Sekolah', 'coa_no' => '600.002',  'coa_category_id' => 'BEBAN PENJUALAN', 'amount' => 0, 'description' => 'BEBAN PENJUALAN', 'type' => 'Debit'],
            ['name' => 'BEBAN TRANSPORTASI', 'coa_no' => '610.000',  'coa_category_id' => 'BEBAN PENJUALAN', 'amount' => 0, 'description' => 'BEBAN PENJUALAN', 'type' => 'Debit'],
            ['name' => 'BBM, Parkir, Tol', 'coa_no' => '610.0001',  'coa_category_id' => 'BEBAN PENJUALAN', 'amount' => 0, 'description' => 'BEBAN PENJUALAN', 'type' => 'Debit'],
            ['name' => 'Ongkos Kirim', 'coa_no' => '610.002',  'coa_category_id' => 'BEBAN PENJUALAN', 'amount' => 0, 'description' => 'BEBAN PENJUALAN', 'type' => 'Debit'],
            ['name' => 'Perjalanan Dinas', 'coa_no' => '610.003',  'coa_category_id' => 'BEBAN PENJUALAN', 'amount' => 0, 'description' => 'BEBAN PENJUALAN', 'type' => 'Debit'],
            ['name' => 'Biaya Kedinasan', 'coa_no' => '610.004',  'coa_category_id' => 'BEBAN PENJUALAN', 'amount' => 0, 'description' => 'BEBAN PENJUALAN', 'type' => 'Debit'],
            ['name' => 'Antar Jemput', 'coa_no' => '610.005',  'coa_category_id' => 'BEBAN PENJUALAN', 'amount' => 0, 'description' => 'BEBAN PENJUALAN', 'type' => 'Debit'],
            ['name' => 'BEBAN PEMELIHARAAN', 'coa_no' => '620.000',  'coa_category_id' => 'BEBAN PENJUALAN', 'amount' => 0, 'description' => 'BEBAN PENJUALAN', 'type' => 'Debit'],
            ['name' => 'B. Pemeliharaan Invetaris', 'coa_no' => '620.001',  'coa_category_id' => 'BEBAN PENJUALAN', 'amount' => 0, 'description' => 'BEBAN PENJUALAN', 'type' => 'Debit'],
            ['name' => 'Biaya Penjualan Lainnya', 'coa_no' => '699.999',  'coa_category_id' => 'BEBAN PENJUALAN', 'amount' => 0, 'description' => 'BEBAN PENJUALAN', 'type' => 'Debit'],

            // KATEGORI BEBAN UMUM & ADMINISTRASI
            ['name' => 'BEBAN GAJI & TUNJANGAN', 'coa_no' => '700.000',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Tunjangan Guru & Staff', 'coa_no' => '700.001',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Fee - Guru Part Time', 'coa_no' => '700.002',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Konsumsi Guru & Staff', 'coa_no' => '700.003',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Makan Siang Guru', 'coa_no' => '700.004',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Makan Siang Siswa', 'coa_no' => '700.005',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'BEBAN PERLENGKAPAN SEKOLAH', 'coa_no' => '710.000',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Internet Sekolah', 'coa_no' => '710.001',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Kebutuhan - Healty Meal', 'coa_no' => '710.003',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Kebutuhan Kantin', 'coa_no' => '710.004',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Kebutuhan Praktek Eca', 'coa_no' => '710.005',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Kebutuhan Sekolah', 'coa_no' => '710.006',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Kebutuhan Uks', 'coa_no' => '710.007',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Lomba Dan Aktivitas Siswa', 'coa_no' => '710.008',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Kebutuhan Graduation', 'coa_no' => '710.009',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'BEBAN KANTOR', 'coa_no' => '720.000',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Fotocopy & Laminating', 'coa_no' => '720.001',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'ATK Sekolah', 'coa_no' => '720.002',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Biaya Rumah Tangga Kantor (RTK)', 'coa_no' => '720.003',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Cleaning Servis', 'coa_no' => '720.004',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Pulsa & Voucher Hp', 'coa_no' => '720.005',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Security', 'coa_no' => '720.006',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Biaya Afiliasi', 'coa_no' => '720.007',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'BEBAN PENGIRIMAN', 'coa_no' => '730.000',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Biaya Pengiriman ', 'coa_no' => '730.001',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Biaya Benda Pos, Meterai', 'coa_no' => '730.002',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'BEBAN ADMINISTRASI BANK', 'coa_no' => '740.000',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Biaya Administrasi Bank', 'coa_no' => '740.001',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Biaya Provisi', 'coa_no' => '740.002',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Biaya Transfer', 'coa_no' => '740.003',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'BEBAN PAJAK/SUMBANGAN/IURAN', 'coa_no' => '750.000',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Biaya Pajak', 'coa_no' => '750.001',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Biaya Pajak Daerah', 'coa_no' => '750.002',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Biaya Sumbangan', 'coa_no' => '750.003',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Biaya Pengurusan & Ijin', 'coa_no' => '750.004',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Biaya Iuran dan Langganan', 'coa_no' => '750.005',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Biaya Retribusi', 'coa_no' => '750.006',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Biaya PPh Final (Tarif Khusus)', 'coa_no' => '750.007',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'BEBAN SEWA', 'coa_no' => '760.000',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Biaya Sewa Tanah dan/atau Bangunan', 'coa_no' => '760.001',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Biaya Sewa Lainnya', 'coa_no' => '760.002',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'BEBAN PEMELIHARAAN & PENYUSUTAN', 'coa_no' => '770.000',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Biaya Pemeliharaan', 'coa_no' => '770.001',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Biaya Penyusutan Bangunan', 'coa_no' => '770.002',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Biaya Penyusutan Kendaraan', 'coa_no' => '770.003',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Biaya Penyusutan Inventaris Sekolah', 'coa_no' => '770.004',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],
            ['name' => 'Biaya Penyusutan Sarana & Instalasi', 'coa_no' => '770.005',  'coa_category_id' => 'BEBAN UMUM & ADMINISTRASI', 'amount' => 0, 'description' => 'BEBAN UMUM & ADMINISTRASI', 'type' => 'Debit'],

            // KATEGORI PENDAPATAN (BEBAN) LAIN-LAIN
            ['name' => 'PENDAPATAN LAIN-LAIN', 'coa_no' => '800.000',  'coa_category_id' => 'PENDAPATAN (BEBAN) LAIN-LAIN', 'amount' => 0, 'description' => 'PENDAPATAN (BEBAN) LAIN-LAIN', 'type' => 'Kredit'],
            ['name' => 'Pendapatan Bunga Bank', 'coa_no' => '800.001',  'coa_category_id' => 'PENDAPATAN (BEBAN) LAIN-LAIN', 'amount' => 0, 'description' => 'PENDAPATAN (BEBAN) LAIN-LAIN', 'type' => 'Kredit'],
            ['name' => 'Pendapatan Bunga Pihak Ketiga', 'coa_no' => '800.002',  'coa_category_id' => 'PENDAPATAN (BEBAN) LAIN-LAIN', 'amount' => 0, 'description' => 'PENDAPATAN (BEBAN) LAIN-LAIN', 'type' => 'Kredit'],
            ['name' => 'Pendapatan Jasa Giro', 'coa_no' => '800.003',  'coa_category_id' => 'PENDAPATAN (BEBAN) LAIN-LAIN', 'amount' => 0, 'description' => 'PENDAPATAN (BEBAN) LAIN-LAIN', 'type' => 'Kredit'],
            ['name' => 'Laba Selisih Kurs', 'coa_no' => '800.004',  'coa_category_id' => 'PENDAPATAN (BEBAN) LAIN-LAIN', 'amount' => 0, 'description' => 'PENDAPATAN (BEBAN) LAIN-LAIN', 'type' => 'Kredit'],
            ['name' => 'Laba Penjualan Aset Tetap', 'coa_no' => '800.005',  'coa_category_id' => 'PENDAPATAN (BEBAN) LAIN-LAIN', 'amount' => 0, 'description' => 'PENDAPATAN (BEBAN) LAIN-LAIN', 'type' => 'Kredit'],
            ['name' => 'BEBAN LAIN-LAIN', 'coa_no' => '810.000',  'coa_category_id' => 'PENDAPATAN (BEBAN) LAIN-LAIN', 'amount' => 0, 'description' => 'PENDAPATAN (BEBAN) LAIN-LAIN', 'type' => 'Debit'],
            ['name' => 'Beban Bunga Bank', 'coa_no' => '810.001',  'coa_category_id' => 'PENDAPATAN (BEBAN) LAIN-LAIN', 'amount' => 0, 'description' => 'PENDAPATAN (BEBAN) LAIN-LAIN', 'type' => 'Debit'],
            ['name' => 'Beban Bunga Pihak Ketiga', 'coa_no' => '810.002',  'coa_category_id' => 'PENDAPATAN (BEBAN) LAIN-LAIN', 'amount' => 0, 'description' => 'PENDAPATAN (BEBAN) LAIN-LAIN', 'type' => 'Debit'],
            ['name' => 'Beban Pajak atas Pendapatan Bunga', 'coa_no' => '810.003',  'coa_category_id' => 'PENDAPATAN (BEBAN) LAIN-LAIN', 'amount' => 0, 'description' => 'PENDAPATAN (BEBAN) LAIN-LAIN', 'type' => 'Debit'],
            ['name' => 'Kerugian Selisih Kurs', 'coa_no' => '810.004',  'coa_category_id' => 'PENDAPATAN (BEBAN) LAIN-LAIN', 'amount' => 0, 'description' => 'PENDAPATAN (BEBAN) LAIN-LAIN', 'type' => 'Debit'],
            ['name' => 'Keuntungan (Kerugian) Penjualan Aset Tetap', 'coa_no' => '810.005',  'coa_category_id' => 'PENDAPATAN (BEBAN) LAIN-LAIN', 'amount' => 0, 'description' => 'PENDAPATAN (BEBAN) LAIN-LAIN', 'type' => 'Debit'],
            ['name' => 'BEBAN PAJAK', 'coa_no' => '900.000',  'coa_category_id' => 'PENDAPATAN (BEBAN) LAIN-LAIN', 'amount' => 0, 'description' => 'PENDAPATAN (BEBAN) LAIN-LAIN', 'type' => 'Debit'],
            ['name' => 'Beban Pajak Kini', 'coa_no' => '900.001',  'coa_category_id' => 'PENDAPATAN (BEBAN) LAIN-LAIN', 'amount' => 0, 'description' => 'PENDAPATAN (BEBAN) LAIN-LAIN', 'type' => 'Debit'],

            // END DATA VERSI INDO


            // ['name' => 'Rekening Bank', 'account_no' => '1-10002', 'account_category_id' => 'Kas & Bank', 'amount' => -4000000.00, 'description' => 'Rekening Bank'],
            // ['name' => 'Kas Di Mesin Kasir', 'account_no' => '1-10003', 'account_category_id' => 'Kas & Bank', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Giro', 'account_no' => '1-10004', 'account_category_id' => 'Kas & Bank', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Piutang Usaha', 'account_no' => '1-10100',  'account_category_id' => 'Akun Piutang', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Piutang Belum Ditagih', 'account_no' => '1-10101',  'account_category_id' => 'Akun Piutang', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Cadangan Kerugian Piutang', 'account_no' => '1-10102',  'account_category_id' => 'Akun Piutang', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Persediaan Barang Makanan', 'account_no' => '1-10200',  'account_category_id' => 'Persediaan', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Persediaan Barang Minuman', 'account_no' => '1-10201',  'account_category_id' => 'Persediaan', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Piutang Lainnya', 'account_no' => '1-10300',  'account_category_id' => 'Aktiva Lancar Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Piutang Karyawan', 'account_no' => '1-10301',  'account_category_id' => 'Aktiva Lancar Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Dana Belum Disetor', 'account_no' => '1-10400',  'account_category_id' => 'Aktiva Lancar Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Aset Lancar Lainnya', 'account_no' => '1-10401',  'account_category_id' => 'Aktiva Lancar Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Biaya Dibayar Dimuka', 'account_no' => '1-10402',  'account_category_id' => 'Aktiva Lancar Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Uang Muka', 'account_no' => '1-10403',  'account_category_id' => 'Aktiva Lancar Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'PPN Masukan', 'account_no' => '1-10500',  'account_category_id' => 'Aktiva Lancar Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Pajak Dibayar Di Muka - PPh 22', 'account_no' => '1-10501',  'account_category_id' => 'Aktiva Lancar Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Pajak Dibayar Di Muka - PPh 23', 'account_no' => '1-10502',  'account_category_id' => 'Aktiva Lancar Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Pajak Dibayar Di Muka - PPh 25', 'account_no' => '1-10503',  'account_category_id' => 'Aktiva Lancar Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Aset Tetap - Tanah', 'account_no' => '1-10700',  'account_category_id' => 'Aktiva Tetap', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Aset Tetap - Bangunan', 'account_no' => '1-10701',  'account_category_id' => 'Aktiva Tetap', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Aset Tetap - Building Improvements', 'account_no' => '1-10702',  'account_category_id' => 'Aktiva Tetap', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Aset Tetap - Kendaraan', 'account_no' => '1-10703',  'account_category_id' => 'Aktiva Tetap', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Aset Tetap - Mesin & Peralatan', 'account_no' => '1-10704',  'account_category_id' => 'Aktiva Tetap', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Aset Tetap - Perlengkapan Kantor', 'account_no' => '1-10705',  'account_category_id' => 'Aktiva Tetap', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Aset Tetap - Aset Sewa Guna Usaha', 'account_no' => '1-10706',  'account_category_id' => 'Aktiva Tetap', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Aset Tak Berwujud', 'account_no' => '1-10707',  'account_category_id' => 'Aktiva Tetap', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Akumulasi Penyusutan - Bangunan', 'account_no' => '1-10751',  'account_category_id' => 'Depresiasi & Amortisasi', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Akumulasi Penyusutan - Building Improvements', 'account_no' => '1-10752',  'account_category_id' => 'Depresiasi & Amortisasi', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Akumulasi penyusutan - Kendaraan', 'account_no' => '1-10753',  'account_category_id' => 'Depresiasi & Amortisasi', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Akumulasi Penyusutan - Mesin & Peralatan', 'account_no' => '1-10754',  'account_category_id' => 'Depresiasi & Amortisasi', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Akumulasi Penyusutan - Peralatan Kantor', 'account_no' => '1-10755',  'account_category_id' => 'Depresiasi & Amortisasi', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Akumulasi Penyusutan - Aset Sewa Guna Usaha', 'account_no' => '1-10756',  'account_category_id' => 'Depresiasi & Amortisasi', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Akumulasi Amortisasi', 'account_no' => '1-10757',  'account_category_id' => 'Depresiasi & Amortisasi', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Investasi', 'account_no' => '1-10800',  'account_category_id' => 'Aktiva Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Hutang Usaha', 'account_no' => '2-20100',  'account_category_id' => 'Akun Hutang', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Hutang Belum Ditagih', 'account_no' => '2-20101',  'account_category_id' => 'Akun Hutang', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Hutang Lain Lain', 'account_no' => '2-20200',  'account_category_id' => 'Kewajiban Lancar Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Hutang Gaji', 'account_no' => '2-20201',  'account_category_id' => 'Kewajiban Lancar Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Hutang Deviden', 'account_no' => '2-20202',  'account_category_id' => 'Kewajiban Lancar Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Pendapatan Diterima Di Muka', 'account_no' => '2-20203',  'account_category_id' => 'Kewajiban Lancar Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Hutang Konsinyasi', 'account_no' => '2-20205',  'account_category_id' => 'Kewajiban Lancar Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Sarana Kantor Terhutang', 'account_no' => '2-20301',  'account_category_id' => 'Kewajiban Lancar Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Bunga Terhutang', 'account_no' => '2-20302',  'account_category_id' => 'Kewajiban Lancar Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Biaya Terhutang Lainnya', 'account_no' => '2-20399',  'account_category_id' => 'Kewajiban Lancar Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Hutang Bank', 'account_no' => '2-20400',  'account_category_id' => 'Kewajiban Lancar Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'PPN Keluaran', 'account_no' => '2-20500',  'account_category_id' => 'Kewajiban Lancar Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Hutang Pajak - PPh 21', 'account_no' => '2-20501',  'account_category_id' => 'Kewajiban Lancar Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Hutang Pajak - PPh 22', 'account_no' => '2-20502',  'account_category_id' => 'Kewajiban Lancar Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Hutang Pajak - PPh 23', 'account_no' => '2-20503',  'account_category_id' => 'Kewajiban Lancar Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Hutang Pajak - PPh 29', 'account_no' => '2-20504',  'account_category_id' => 'Kewajiban Lancar Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Hutang Pajak', 'account_no' => '2-20599',  'account_category_id' => 'Kewajiban Lancar Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Hutang Dari Pemegang Saham', 'account_no' => '2-20600',  'account_category_id' => 'Kewajiban Lancar Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Kewajiban Lancar Lainnya', 'account_no' => '2-20601',  'account_category_id' => 'Kewajiban Lancar Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Kewajiban Manfaat Karyawan', 'account_no' => '2-20700',  'account_category_id' => 'Kewajiban Jangka Panjang', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Modal Saham', 'account_no' => '3-30000',  'account_category_id' => 'Ekuitas', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Tambahan Modal Disetor', 'account_no' => '3-30001',  'account_category_id' => 'Ekuitas', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Laba Ditahan', 'account_no' => '3-30100',  'account_category_id' => 'Ekuitas', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Deviden', 'account_no' => '3-30200',  'account_category_id' => 'Ekuitas', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Pendapatan Komprehensif Lainnya', 'account_no' => '3-30300',  'account_category_id' => 'Ekuitas', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Ekuitas Saldo Awal', 'account_no' => '3-30999',  'account_category_id' => 'Ekuitas', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Pendapatan Makanan', 'account_no' => '4-40000',  'account_category_id' => 'Pendapatan', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Pendapatan Minuman', 'account_no' => '4-40001',  'account_category_id' => 'Pendapatan', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Pendapatan Katering', 'account_no' => '4-40002',  'account_category_id' => 'Pendapatan', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Diskon Penjualan', 'account_no' => '4-40100',  'account_category_id' => 'Pendapatan', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Retur Penjualan', 'account_no' => '4-40200',  'account_category_id' => 'Pendapatan', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Pendapatan Belum Ditagih', 'account_no' => '4-40201',  'account_category_id' => 'Pendapatan', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Beban Pokok Pendapatan Makanan', 'account_no' => '5-50000',  'account_category_id' => 'Harga Pokok Penjualan', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Beban Pokok Pendapatan Minuman', 'account_no' => '5-50001',  'account_category_id' => 'Harga Pokok Penjualan', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Beban Pokok Pendapatan Waste', 'account_no' => '5-50002',  'account_category_id' => 'Harga Pokok Penjualan', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Diskon Pembelian', 'account_no' => '5-50100',  'account_category_id' => 'Harga Pokok Penjualan', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Retur Pembelian', 'account_no' => '5-50200',  'account_category_id' => 'Harga Pokok Penjualan', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Pengiriman & Pengangkutan', 'account_no' => '5-50300',  'account_category_id' => 'Harga Pokok Penjualan', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Biaya Impor', 'account_no' => '5-50400',  'account_category_id' => 'Harga Pokok Penjualan', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Biaya Produksi', 'account_no' => '5-50500',  'account_category_id' => 'Harga Pokok Penjualan', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Biaya Penjualan', 'account_no' => '6-60000',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Iklan & Promosi', 'account_no' => '6-60001',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Komisi & Fee', 'account_no' => '6-60002',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Bensin, Tol dan Parkir - Penjualan', 'account_no' => '6-60003',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Perjalanan Dinas - Penjualan', 'account_no' => '6-60004',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Komunikasi - Penjualan', 'account_no' => '6-60005',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Marketing Lainnya', 'account_no' => '6-60006',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Seragam Pegawai', 'account_no' => '6-60007',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Biaya Kemitraan', 'account_no' => '6-60008',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Biaya Royalti', 'account_no' => '6-60009',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Biaya Umum & Administratif', 'account_no' => '6-60100',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Gaji', 'account_no' => '6-60101',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Upah', 'account_no' => '6-60102',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Makanan & Transportasi', 'account_no' => '6-60103',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Lembur', 'account_no' => '6-60104',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Pengobatan', 'account_no' => '6-60105',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'THR & Bonus', 'account_no' => '6-60106',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Jamsostek', 'account_no' => '6-60107',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Insentif', 'account_no' => '6-60108',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Pesangon', 'account_no' => '6-60109',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Manfaat dan Tunjangan Lain', 'account_no' => '6-60110',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Donasi', 'account_no' => '6-60200',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Hiburan', 'account_no' => '6-60201',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Bensin, Tol dan Parkir - Umum', 'account_no' => '6-60202',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Perbaikan & Pemeliharaan', 'account_no' => '6-60203',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Perjalanan Dinas - Umum', 'account_no' => '6-60204',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Makanan', 'account_no' => '6-60205',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Komunikasi Umum', 'account_no' => '6-60206',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Iuran & Langganan', 'account_no' => '6-60207',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Asuransi', 'account_no' => '6-60208',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Legal & Profesional', 'account_no' => '6-60209',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Beban Manfaat Karyawan', 'account_no' => '6-60210',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Sarana Kantor', 'account_no' => '6-60211',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Pelatihan & Pengembangan', 'account_no' => '6-60212',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Beban Piutang Tak Tertagih', 'account_no' => '6-60213',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Pajak dan Perizinan', 'account_no' => '6-60214',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Denda', 'account_no' => '6-60215',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Listrik', 'account_no' => '6-60217',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Air', 'account_no' => '6-60218',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Biaya Sistem Kasir', 'account_no' => '6-60219',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'IPL', 'account_no' => '6-60220',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Langganan Software', 'account_no' => '6-60221',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Beban Kantor', 'account_no' => '6-60300',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Alat Tulis Kantor & Printing', 'account_no' => '6-60301',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Bea Materai', 'account_no' => '6-60302',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Keamanan dan Kebersihan', 'account_no' => '6-60303',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Supplies dan Material', 'account_no' => '6-60304',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Pemborong', 'account_no' => '6-60305',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Biaya Sewa - Bangunan', 'account_no' => '6-60400',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Biaya Sewa - Kendaraan', 'account_no' => '6-60401',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Biaya Sewa - Operasional', 'account_no' => '6-60402',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Biaya Sewa - Lain - Lain', 'account_no' => '6-60403',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Penyusutan - Bangunan', 'account_no' => '6-60500',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Penyusutan - Perbaikan Bangunan', 'account_no' => '6-60501',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Penyusutan - Kendaraan', 'account_no' => '6-60502',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Penyusutan - Mesin & Peralatan', 'account_no' => '6-60503',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Penyusutan - Peralatan Kantor', 'account_no' => '6-60504',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Penyusutan - Aset Sewa Guna Usaha', 'account_no' => '6-60599',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Pengeluaran Barang Rusak', 'account_no' => '6-60216',  'account_category_id' => 'Beban', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Pendapatan Bunga - Bank', 'account_no' => '7-70000',  'account_category_id' => 'Pendapatan Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Pendapatan Bunga - Deposito', 'account_no' => '7-70001',  'account_category_id' => 'Pendapatan Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Pendapatan Komisi - Barang Konsinyasi', 'account_no' => '7-70002',  'account_category_id' => 'Pendapatan Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Pembulatan', 'account_no' => '7-70003',  'account_category_id' => 'Pendapatan Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Pendapatan Lain - lain', 'account_no' => '7-70099',  'account_category_id' => 'Pendapatan Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Beban Bunga', 'account_no' => '8-80000',  'account_category_id' => 'Beban Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Provinsi', 'account_no' => '8-80001',  'account_category_id' => 'Beban Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => '(Laba)/Rugi Pelepasan Aset Tetap', 'account_no' => '8-80002',  'account_category_id' => 'Beban Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Penyesuaian Persediaan', 'account_no' => '8-80100',  'account_category_id' => 'Beban Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Beban Lain - lain', 'account_no' => '8-80999',  'account_category_id' => 'Beban Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Beban Pajak - Kini', 'account_no' => '8-90000',  'account_category_id' => 'Beban Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],
            // ['name' => 'Beban Pajak - Tangguhan', 'account_no' => '8-90001',  'account_category_id' => 'Beban Lainnya', 'amount' => 0.00, 'description' => 'Kas di Mesin Kasir'],

            // START VERSI INGGRIS
            // ['name' => 'Cash', 'account_no' => '1-10001',  'account_category_id' => 'Cash & Bank', 'amount' => 4000000.00, 'description' => 'Kas'],
            // ['name' => 'Bank Account', 'account_no' => '1-10002', 'account_category_id' => 'Cash & Bank', 'amount' => -4000000.00, 'description' => 'Rekening Bank'],
            // ['name' => 'Cash in Register', 'account_no' => '1-10003', 'account_category_id' => 'Cash & Bank', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Giro', 'account_no' => '1-10004', 'account_category_id' => 'Cash & Bank', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Accounts Receivable', 'account_no' => '1-10100',  'account_category_id' => 'Accounts Receivable', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Unbilled Receivables', 'account_no' => '1-10101',  'account_category_id' => 'Accounts Receivable', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Allowance for Doubtful Accounts', 'account_no' => '1-10102',  'account_category_id' => 'Accounts Receivable', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Food Inventory', 'account_no' => '1-10200',  'account_category_id' => 'Inventory', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Beverage Inventory', 'account_no' => '1-10201',  'account_category_id' => 'Inventory', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Other Receivables', 'account_no' => '1-10300',  'account_category_id' => 'Other Current Assets', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Employee Receivables', 'account_no' => '1-10301',  'account_category_id' => 'Other Current Assets', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Undeposited Funds', 'account_no' => '1-10400',  'account_category_id' => 'Other Current Assets', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Other Current Assets', 'account_no' => '1-10401',  'account_category_id' => 'Other Current Assets', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Prepaid Expenses', 'account_no' => '1-10402',  'account_category_id' => 'Other Current Assets', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Advances', 'account_no' => '1-10403',  'account_category_id' => 'Other Current Assets', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Input VAT', 'account_no' => '1-10500',  'account_category_id' => 'Other Current Assets', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Prepaid Tax - PPh 22', 'account_no' => '1-10501',  'account_category_id' => 'Other Current Assets', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Prepaid Tax - PPh 23', 'account_no' => '1-10502',  'account_category_id' => 'Other Current Assets', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Prepaid Tax - PPh 25', 'account_no' => '1-10503',  'account_category_id' => 'Other Current Assets', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Fixed Assets - Land', 'account_no' => '1-10700',  'account_category_id' => 'Fixed Assets', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Fixed Assets - Buildings', 'account_no' => '1-10701',  'account_category_id' => 'Fixed Assets', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Fixed Assets - Building Improvements', 'account_no' => '1-10702',  'account_category_id' => 'Fixed Assets', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Fixed Assets - Vehicles', 'account_no' => '1-10703',  'account_category_id' => 'Fixed Assets', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Fixed Assets - Machinery & Equipment', 'account_no' => '1-10704',  'account_category_id' => 'Fixed Assets', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Fixed Assets - Office Equipment', 'account_no' => '1-10705',  'account_category_id' => 'Fixed Assets', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Fixed Assets - Leased Assets', 'account_no' => '1-10706',  'account_category_id' => 'Fixed Assets', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Intangible Assets', 'account_no' => '1-10707',  'account_category_id' => 'Fixed Assets', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Accumulated Depreciation - Buildings', 'account_no' => '1-10751',  'account_category_id' => 'Depreciation & Amortization', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Accumulated Depreciation - Building Improvements', 'account_no' => '1-10752',  'account_category_id' => 'Depreciation & Amortization', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Accumulated Depreciation - Vehicles', 'account_no' => '1-10753',  'account_category_id' => 'Depreciation & Amortization', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Accumulated Depreciation - Machinery & Equipment', 'account_no' => '1-10754',  'account_category_id' => 'Depreciation & Amortization', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Accumulated Depreciation - Office Equipment', 'account_no' => '1-10755',  'account_category_id' => 'Depreciation & Amortization', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Accumulated Depreciation - Leased Assets', 'account_no' => '1-10756',  'account_category_id' => 'Depreciation & Amortization', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Accumulated Amortization', 'account_no' => '1-10757',  'account_category_id' => 'Depreciation & Amortization', 'amount' => 0.00, 'description' => 'test'],

            // ['name' => 'Investment', 'account_no' => '1-10800',  'account_category_id' => 'Other Assets', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Accounts Payable', 'account_no' => '2-20100',  'account_category_id' => 'Accounts Payable', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Unbilled Payables', 'account_no' => '2-20101',  'account_category_id' => 'Accounts Payable', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Other Payables', 'account_no' => '2-20200',  'account_category_id' => 'Other Current Liabilities', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Wages Payable', 'account_no' => '2-20201',  'account_category_id' => 'Other Current Liabilities', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Dividends Payable', 'account_no' => '2-20202',  'account_category_id' => 'Other Current Liabilities', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Unearned Revenue', 'account_no' => '2-20203',  'account_category_id' => 'Other Current Liabilities', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Consignment Payable', 'account_no' => '2-20205',  'account_category_id' => 'Other Current Liabilities', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Office Supplies Payable', 'account_no' => '2-20301',  'account_category_id' => 'Other Current Liabilities', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Interest Payable', 'account_no' => '2-20302',  'account_category_id' => 'Other Current Liabilities', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Other Accrued Expenses', 'account_no' => '2-20399',  'account_category_id' => 'Other Current Liabilities', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Bank Loan', 'account_no' => '2-20400',  'account_category_id' => 'Other Current Liabilities', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Output VAT', 'account_no' => '2-20500',  'account_category_id' => 'Other Current Liabilities', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Tax Payable - PPh 21', 'account_no' => '2-20501',  'account_category_id' => 'Other Current Liabilities', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Tax Payable - PPh 22', 'account_no' => '2-20502',  'account_category_id' => 'Other Current Liabilities', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Tax Payable - PPh 23', 'account_no' => '2-20503',  'account_category_id' => 'Other Current Liabilities', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Tax Payable - PPh 29', 'account_no' => '2-20504',  'account_category_id' => 'Other Current Liabilities', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Tax Payable', 'account_no' => '2-20599',  'account_category_id' => 'Other Current Liabilities', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Loan from Shareholders', 'account_no' => '2-20600',  'account_category_id' => 'Other Current Liabilities', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Other Current Liabilities', 'account_no' => '2-20601',  'account_category_id' => 'Other Current Liabilities', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Employee Benefits Liability', 'account_no' => '2-20700',  'account_category_id' => 'Long-term Liabilities', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Share Capital', 'account_no' => '3-30000',  'account_category_id' => 'Equity', 'amount' => 0.00, 'description' => 'test'],
            // ['name' => 'Additional Paid-In Capital', 'account_no' => '3-30001',  'account_category_id' => 'Equity', 'amount' => 0.00, 'description' => 'test'],

            // ['name' => 'Dividend', 'account_no' => '3-30200', 'account_category_id' => 'Equity', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Other Comprehensive Income', 'account_no' => '3-30300', 'account_category_id' => 'Equity', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Beginning Balance Equity', 'account_no' => '3-30999', 'account_category_id' => 'Equity', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Food Revenue', 'account_no' => '4-40000', 'account_category_id' => 'Revenue', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Beverage Revenue', 'account_no' => '4-40001', 'account_category_id' => 'Revenue', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Catering Revenue', 'account_no' => '4-40002', 'account_category_id' => 'Revenue', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Sales Discount', 'account_no' => '4-40100', 'account_category_id' => 'Revenue', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Sales Return', 'account_no' => '4-40200', 'account_category_id' => 'Revenue', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Unbilled Revenue', 'account_no' => '4-40201', 'account_category_id' => 'Revenue', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Cost of Food Revenue', 'account_no' => '5-50000', 'account_category_id' => 'Cost of Goods Sold (COGS)', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Cost of Beverage Revenue', 'account_no' => '5-50001', 'account_category_id' => 'Cost of Goods Sold (COGS)', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Cost of Waste Revenue', 'account_no' => '5-50002', 'account_category_id' => 'Cost of Goods Sold (COGS)', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Purchase Discount', 'account_no' => '5-50100', 'account_category_id' => 'Cost of Goods Sold (COGS)', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Purchase Return', 'account_no' => '5-50200', 'account_category_id' => 'Cost of Goods Sold (COGS)', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Shipping & Handling', 'account_no' => '5-50300', 'account_category_id' => 'Cost of Goods Sold (COGS)', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Import Costs', 'account_no' => '5-50400', 'account_category_id' => 'Cost of Goods Sold (COGS)', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Production Costs', 'account_no' => '5-50500', 'account_category_id' => 'Cost of Goods Sold (COGS)', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Sales Expenses', 'account_no' => '6-60000', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Advertising & Promotion', 'account_no' => '6-60001', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Commissions & Fees', 'account_no' => '6-60002', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Fuel, Toll, and Parking - Sales', 'account_no' => '6-60003', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Business Travel - Sales', 'account_no' => '6-60004', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Communication - Sales', 'account_no' => '6-60005', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Other Marketing', 'account_no' => '6-60006', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Employee Uniforms', 'account_no' => '6-60007', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Partnership Costs', 'account_no' => '6-60008', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Royalty Costs', 'account_no' => '6-60009', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'General & Administrative Expenses', 'account_no' => '6-60100', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Salaries', 'account_no' => '6-60101', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Wages', 'account_no' => '6-60102', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Food & Transportation', 'account_no' => '6-60103', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Overtime', 'account_no' => '6-60104', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Medical', 'account_no' => '6-60105', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'THR & Bonus', 'account_no' => '6-60106', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Social Security', 'account_no' => '6-60107', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Incentives', 'account_no' => '6-60108', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Severance Pay', 'account_no' => '6-60109', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Other Benefits and Allowances', 'account_no' => '6-60110', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Donations', 'account_no' => '6-60200', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Entertainment', 'account_no' => '6-60201', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Fuel, Toll, and Parking - General', 'account_no' => '6-60202', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Repairs & Maintenance', 'account_no' => '6-60203', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Business Travel - General', 'account_no' => '6-60204', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Food', 'account_no' => '6-60205', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Communication - General', 'account_no' => '6-60206', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Subscriptions & Memberships', 'account_no' => '6-60207', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Insurance', 'account_no' => '6-60208', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Legal & Professional', 'account_no' => '6-60209', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Employee Benefits Expense', 'account_no' => '6-60210', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Office Facilities', 'account_no' => '6-60211', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Training & Development', 'account_no' => '6-60212', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Bad Debt Expense', 'account_no' => '6-60213', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Taxes and Licenses', 'account_no' => '6-60214', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Penalties', 'account_no' => '6-60215', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Electricity', 'account_no' => '6-60217', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Water', 'account_no' => '6-60218', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'POS System Costs', 'account_no' => '6-60219', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Service Charges', 'account_no' => '6-60220', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Software Subscription', 'account_no' => '6-60221', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Office Expenses', 'account_no' => '6-60300', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Office Supplies & Printing', 'account_no' => '6-60301', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Stamp Duty', 'account_no' => '6-60302', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Security and Cleaning', 'account_no' => '6-60303', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Supplies and Materials', 'account_no' => '6-60304', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Contractor Costs', 'account_no' => '6-60305', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Rent Expense - Building', 'account_no' => '6-60400', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Rent Expense - Vehicle', 'account_no' => '6-60401', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Rent Expense - Operational', 'account_no' => '6-60402', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Rent Expense - Miscellaneous', 'account_no' => '6-60403', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Depreciation - Building', 'account_no' => '6-60500', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Depreciation - Building Improvements', 'account_no' => '6-60501', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Depreciation - Vehicle', 'account_no' => '6-60502', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Depreciation - Machinery & Equipment', 'account_no' => '6-60503', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Depreciation - Office Equipment', 'account_no' => '6-60504', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Depreciation - Leasehold Assets', 'account_no' => '6-60599', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Damaged Goods Write-Off', 'account_no' => '6-60216', 'account_category_id' => 'Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Interest Income - Bank', 'account_no' => '7-70000', 'account_category_id' => 'Other Income', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Interest Income - Deposits', 'account_no' => '7-70001', 'account_category_id' => 'Other Income', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Commission Income - Consignment Goods', 'account_no' => '7-70002', 'account_category_id' => 'Other Income', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Rounding', 'account_no' => '7-70003', 'account_category_id' => 'Other Income', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Miscellaneous Income', 'account_no' => '7-70099', 'account_category_id' => 'Other Income', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Interest Expense', 'account_no' => '8-80000', 'account_category_id' => 'Other Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Provinces', 'account_no' => '8-80001', 'account_category_id' => 'Other Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => '(Profit)/Loss on Disposal of Fixed Assets', 'account_no' => '8-80002', 'account_category_id' => 'Other Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Inventory Adjustments', 'account_no' => '8-80100', 'account_category_id' => 'Other Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Other Expenses', 'account_no' => '8-80999', 'account_category_id' => 'Other Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Current Tax Expense', 'account_no' => '8-90000', 'account_category_id' => 'Other Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],
            // ['name' => 'Deferred Tax Expense', 'account_no' => '8-90001', 'account_category_id' => 'Other Expenses', 'amount' => 0.00, 'description' => 'Cash at Cash Register'],

            // END VERSI INGGRIS 

        ];

        // Map category names to category ids
        foreach ($accounts as &$account) {
            $account['coa_category_id'] = $categories[$account['coa_category_id']];
        }

        // Insert accounts into the accountnumbers table
        DB::table('coas')->insert($accounts);
    }
}
